Avatar/Models/Classe.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Avatar.Models
{
    public class Classe
    {      
        public string NomeClasse { get; set; }
        public  int Forca { get; set; }
        public int Destreza { get; set; }
        public int Inteligencia { get; set; }

    }
}

Avatar/Models/Compra.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Avatar.Models
{
    public class Compra
    {
        public int Id { get; set; }
        public string Cpf { get; set; }
        public string FormaPagamento { get; set; }
        public string NomeComprador { get; set; }
        public DateTime DataCompra { get; set; }



    }
}

Avatar/Models/ContaUsuario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Avatar.Models
{
    public class ContaUsuario
    {

        public  int Id { get; set; }
        public string NomeUsuario { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public bool StatusConta { get; set; }
        public DateTime DataCriacao { get; set; }
        public virtual Personagem Personagem { get; set; }
        public int IdPersonagem { get; set; }

        public List<Personagem> ListaPersonagem; // atenção

    }
}

Avatar/Models/Personagem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Avatar.Models
{
    public class Personagem
    {
      
       public int Id { get; set; }
       public string Nome { get; set; }
       public string Sexo { get; set; }
       public string Url { get; set; }
       public virtual Classe Classe { get; set; }

    }
}

Avatar/Controllers/ContaUsuarioController.cs
using Avatar.Dao;
using Avatar.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Avatar.Controllers
{
    public class ContaUsuarioController : Controller
    {
        private ContaUsuarioContext db = new ContaUsuarioContext();
        // GET: ContaUsuario
        public ActionResult Index()
        {
            return View(db.ContasUsuarios.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ContaUsuario contaUsuario)
        {
            if (ModelState.IsValid)
            {
                db.ContasUsuarios.Add(contaUsuario);
                db.SaveChanges();
                return RedirectToAction("Index");

            }

            return View(contaUsuario);

        }

        public ActionResult Edit(int id)
        {
            return View(db.ContasUsuarios.First(p => p.Id == id));

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ContaUsuario contaUsuario)
        {
            if (ModelState.IsValid)
            {
                ContaUsuario contaUpdate = db.ContasUsuarios.First(p => p.Id == contaUsuario.Id);
                contaUpdate.NomeUsuario = contaUsuario.NomeUsuario;
                contaUpdate.Email = contaUsuario.Email;
                contaUpdate.Senha = contaUsuario.Senha;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(contaUsuario);

        }


        public ActionResult Details(int id)
        {
            return View(db.ContasUsuarios.First(p => p.Id == id));

        }

        public ActionResult Delete(int id)
        {
            return View(db.ContasUsuarios.First(p => p.Id == id));

        }

        [HttpPost , ActionName("Delete") ]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int id)
        {

            var conta = db.ContasUsuarios.First(c => c.Id == id);
            db.ContasUsuarios.Remove(conta);
            db.SaveChanges();
            return RedirectToAction("Index");

        }

    }
}

Avatar/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Avatar.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Avatar/Controllers/PersonagemController.cs
using Avatar.Dao;
using Avatar.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Avatar.Controllers
{
    public class PersonagemController : Controller
    {
        private PersonagemContext db = new PersonagemContext();
        // GET: Personagem
        public ActionResult Index()
        {
            return View(db.Personagens.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Personagem personagem)
        {
            if (ModelState.IsValid)
            {
                db.Personagens.Add(personagem);
                db.SaveChanges();
                return RedirectToAction("Index");

            }

            return View(personagem);

        }

            public ActionResult Edit(int id)
        {
            return View(db.Personagens.First(p => p.Id == id));

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Personagem personagem)
        {
            if (ModelState.IsValid)
            {
                Personagem personagemUpdate = db.Personagens.First(p => p.Id == personagem.Id);
                personagemUpdate.Nome = personagem.Nome;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(personagem);

        }

       
        public ActionResult Details(int id)
        {
            return View(db.Personagens.First(p => p.Id == id));
        }

    }
}

Avatar/Views/ContaUsuario/Create.cshtml
@model Avatar.Models.ContaUsuario


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ContaUsuario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NomeUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeUsuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeUsuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusConta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.StatusConta)
                    @Html.ValidationMessageFor(model => model.StatusConta, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataCriacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataCriacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataCriacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdPersonagem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdPersonagem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdPersonagem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Avatar/Views/ContaUsuario/Delete.cshtml
@model Avatar.Models.ContaUsuario

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ContaUsuario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomeUsuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeUsuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Senha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Senha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatusConta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatusConta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataCriacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataCriacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdPersonagem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdPersonagem)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Avatar/Views/ContaUsuario/DeleteConfirm.cshtml
@model Avatar.Models.ContaUsuario

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ContaUsuario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomeUsuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeUsuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Senha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Senha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatusConta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatusConta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataCriacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataCriacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdPersonagem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdPersonagem)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Avatar/Views/ContaUsuario/Details.cshtml
@model Avatar.Models.ContaUsuario

<div>
    <h4>ContaUsuario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomeUsuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeUsuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Senha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Senha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatusConta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatusConta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataCriacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataCriacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdPersonagem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdPersonagem)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Avatar/Views/ContaUsuario/Edit.cshtml
@model Avatar.Models.ContaUsuario


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ContaUsuario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.NomeUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeUsuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeUsuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusConta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.StatusConta)
                    @Html.ValidationMessageFor(model => model.StatusConta, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataCriacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataCriacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataCriacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdPersonagem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdPersonagem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdPersonagem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Avatar/Views/ContaUsuario/Index.cshtml
@model IEnumerable<Avatar.Models.ContaUsuario>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NomeUsuario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Senha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StatusConta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataCriacao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdPersonagem)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NomeUsuario)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Senha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StatusConta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataCriacao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdPersonagem)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Avatar/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Avatar/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Avatar/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Avatar/Views/Personagem/Create.cshtml
@model Avatar.Models.Personagem

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Personagem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sexo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Avatar/Views/Personagem/Details.cshtml
@model Avatar.Models.Personagem

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Personagem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Url)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Avatar/Views/Personagem/Edit.cshtml
@model Avatar.Models.Personagem

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Personagem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sexo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Avatar/Views/Personagem/Index.cshtml
@model IEnumerable<Avatar.Models.Personagem>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
   
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sexo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Url)
           

        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sexo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Url)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
           
        </td>
    </tr>
}

</table>

Avatar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AvaGame", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Historia", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Avatar", "Index", "Personagem")</li>
                    <li>@Html.ActionLink("Usuario", "Index", "ContaUsuario")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>